source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'pg'

# Use Puma as the app server
gem 'puma', '~> 3.0'

gem 'active_model_serializers'
gem 'will_paginate', git: 'https://github.com/jonatack/will_paginate.git'
gem 'devise'
gem 'omniauth'
gem 'devise_token_auth'
gem 'rack-cors', :require => 'rack/cors'

gem 'jquery-rails'
gem 'turbolinks'
gem 'uglifier'
gem 'awesome_print' # pretty print ruby objects

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  gem 'rails-erd'
  gem 'dotenv'
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
